version: "3"

services:
  gamerban: &django
    restart: always
    build: ./
    volumes:
      - ./app/:/usr/src/app/
    env_file: .env
    environment:
      - DEBUG=1
    ports:
      - 8009:8000
    