version: "3"

services:
  gamerban: &django
    restart: always
    build: docker/local/
    volumes:
      - ./app/:/usr/src/app/
    env_file: ./app/.env
    environment:
      - DEBUG=1
    ports:
      - 8009:8000
    