version: "3"

services:
  gamerban: &django
    restart: always
    build: ./
    volumes:
      - ./:/usr/src/app/
    env_file: .env
    environment:
      - DEBUG=0
    ports:
      - 80:8000
    command: gunicorn gamerban.wsgi:application --bind 0.0.0.0:8000