# Generated by Django 4.1.4 on 2022-12-15 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150, verbose_name='razón del ban')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='fecha del ban')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='game_bans', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_bans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
