# Generated by Django 4.1.4 on 2022-12-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='reason',
            field=models.CharField(choices=[('LANGUAGE', 'Foul language'), ('CHEATING', 'Cheating'), ('HARRASMENT', 'Harrasment'), ('OTHER', 'Other')], default='CHEATING', max_length=150, verbose_name='razón del ban'),
        ),
    ]
